### ISSUE TITLE
Client raises TypeError when API responds with 204

### ISSUE THREAD

**Issue by foxy-eyed** [appwrite/sdk-for-ruby#6]
Hi!
SDK raises exception when calling `Appwrite::Database#delete_document` because API endpoint responds with `204 No Content` without body, but `Appwrite::Client` expects JSON and tries to parse it.

Ruby version: `3.0.2`
SDK version: `2.4.0`

Trace:
```
/Users/anna/.rbenv/versions/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `initialize': no implicit conversion of nil into String (TypeError)
	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `new'
	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `parse'
	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/appwrite-2.4.0/lib/appwrite/client.rb:110:in `fetch'
	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/appwrite-2.4.0/lib/appwrite/client.rb:67:in `call'
	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/appwrite-2.4.0/lib/appwrite/services/database.rb:294:in `delete_document'
```

I suppose it is common problem for all `DELETE` endpoints such as `Appwrite::Database#delete_document`, `Appwrite::Storage#delete_file`, `Appwrite::Storage#delete_collection`

I could try to fix and open PR if it's ok)

**Comment by jacobprudhomme** [comment]
Can confirm it happens with other `DELETE` endpoints too. Happens to me when I try deleting a file from storage.

**Comment by eldadfux** [comment]
Fixed at https://github.com/appwrite/sdk-generator/issues/289
